SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
BEGIN TRANSACTION;
SELECT * FROM Bundle WHERE Price < 500.00; -- Count how many rows you get. Switch to Session A.
WAITFOR DELAY '00:00:08';
SELECT * FROM Bundle WHERE Price < 500.00;
COMMIT;

-- FIX -> using SERIALIZABLE
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;