SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION;
SELECT Name, Price FROM Bundle WHERE Name = 'Summer Bundle';

WAITFOR DELAY '00:00:08';
SELECT Name, Price FROM Bundle WHERE Name = 'Summer Bundle';

COMMIT;